version: "3.3"
services:
  nginx:
    container_name: ws_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  php:
    container_name: ws_php
    build: ./php
    volumes:
      - ./php/src:/var/www
  
  mysql:
    container_name: ws_mysql
    image: mysql:latest
    environment:
      # DBの名前
      MYSQL_DATABASE: vul_db
      # 全権限を持つ、実質rootアカウント
      MYSQL_USER: user
      # MYSQL_USERのパスワード
      MYSQL_PASSWORD: password
      # rootアカウントのパスワード
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d